name: advent_of_code
description: Advent of Code 2022
version: 1.0.0
homepage: https://adventofcode.com/2022

environment:
  sdk: ">=2.18.4 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
